### PR TITLE
Dynamic scopes for OIDC

### LINKED ISSUE #1363: Allow Custom oidc.userIdentifier field
**Description**

When using a custom scope for the `userIdentifier` in the OIDC config it fails because the retrived values are hard coded in `oidc.go` and will therefor not work. Was trying to use the common `given_name` as `userIdentifier` but it failed.

**Expected behaviour**

I would expect it to be able to receive and use every custom scope the OIDC provider can provide.

**What is happening instead?**

You are met with this when trying to login:
`{"status":500,"message":"no valid username found in ID token or UserInfo response from claims"}`

and the debug logs say this:
`2025/10/15 20:18:26 [INFO ] write.go:261: GET     | 302 | REDACTED_IP:43478 | N/A          | 0ms          | "/api/auth/oidc/login?redirect=%2Ffiles%2F"`
`2025/10/15 20:18:26 [DEBUG] oidc.go:185: ID token found in token response, attempting verification.`
`2025/10/15 20:18:26 [DEBUG] oidc.go:202: ID Token verified and claims decoded: {Name:REDACTED_NAME PreferredUsername:REDACTED_PREF_USERNAME Username: Email:REDACTED_EMAIL Sub:6285bff64df919759532646e38e106cf320ff20ef024bf1371559be6c5c636c5 Phone: Groups:[REDACTED_LIST_OF_GROUPS]}`
`2025/10/15 20:18:26 [ERROR] write.go:261: GET     | 500 | REDACTED_IP:43478 | N/A          | 498ms        | "/api/auth/oidc/callback?code=35c51f2d99e84b24ad2dbd3db0bd629e&state=qhhg4k0wj4x3tlsm%3A%2Ffiles%2F"`

**Additional context**

What I can determin from the file `oidc.go` it only allows some pre-determined values.

**How to reproduce?**

Set the config setting `auth.methods.oidc.userIdentifier` equal to something else then the hardcoded alternative, i.e `given_name` and then try to login.

**Files**

### PR DESCRIPTION
**Pull request by WilliamSoderberg**
**Description**

Implementation of dynamically loaded scopes in the OIDC connection process. Enabling custom scopes to be used as username.

Closes #1363 

According to the [contributing guide](https://github.com/gtsteffaniak/filebrowser/wiki/Contributing#contributing-as-an-unofficial-contributor), A PR should contain:

- [x] A clear description of why it was opened.
- [x] A short title that best describes the change.
- [x] Must pass unit and integration tests, which can be run checked locally prior to opening a PR.
- [x] Any additional details for functionality not covered by tests.

**Additional Details**
Except for the already provide oidc_test, test were made using non exsistent scopes to test for failure.

When invalid `userIdentifier` is used:
```json
{"status":500,"message":"no valid username found for identifier 'test'"}
```

### CODE REVIEW

File: backend/http/oidc.go [hunk 1]
```diff
@@ -247,22 +221,20 @@ func oidcCallbackHandler(w http.ResponseWriter, r *http.Request, d *requestConte
...
-			loginUsername = userdata.Phone
+	}
+
+	// --- Determine login username dynamically ---
+	if val, ok := userdata.Claims[oidcCfg.UserIdentifier]; ok {
+		switch v := val.(type) {
+		case string:
+			loginUsername = v
+		default:
+			loginUsername = fmt.Sprintf("%v", v)
```
Comment (gtsteffaniak) [inline backend/http/oidc.go]: I think this should error if its not a string

**Comment by gtsteffaniak** [comment]
thanks for the work to contribute this feature. I do plan to merge this, but it will go on the beta track. I am not making any disruptive changes until I have a stable release track ready.

Then this will merge to beta so it won't affect stable.

File: backend/http/oidc.go (hunk 1 above)
Comment (Swedish-Wiking) [reply backend/http/oidc.go]: Removed the default and made it a if-statement instead.
