### PR TITLE
Add .devcontainer and fix 'make dev' startup

### LINKED ISSUE #2280: Can't start dev server with make dev
**Description**
I tried to start the dev server but I can't do it using `make dev`.

```bash
Starting dev servers... Press Ctrl+C to stop.
make: *** [makefile:51: dev] Terminated
```

I noticed this two lines were added in 09210d449073f5abd52de3be5e89beee74dff7f2

https://github.com/gtsteffaniak/filebrowser/blob/d2165ec0c3962325e3e5af5f2c1e2cb5ce42ffc6/makefile#L51-L52

And by commenting out them is working again.

### PR DESCRIPTION
**Pull request by nebula-it**
**Description**

According to the [contributing guide](https://github.com/gtsteffaniak/filebrowser/wiki/Contributing#contributing-as-an-unofficial-contributor), A PR should contain:

- [x] A clear description of why it was opened.
- [x] A short title that best describes the change.
- [x] Must pass unit and integration tests, which can be run checked locally prior to opening a PR.
- [x] Any additional details for functionality not covered by tests.

**Additional Details**

This PR adds:
* A .devcontainer file to simplify dev environment
* Fixes: https://github.com/gtsteffaniak/filebrowser/issues/2280
* Removed logging for `/health` endpoint so it does not clutter logs

### CODE REVIEW

File: backend/http/middleware.go [hunk 1]
```diff
@@ -827,14 +827,17 @@ func LoggingMiddleware(next http.Handler) http.Handler {
...
 		// Use the StatusCode from wrappedWriter, which might have been set to 500 by the recover logic
-		logger.Api(wrappedWriter.StatusCode,
-			fmt.Sprintf("%-7s | %3d | %-15s | %-12s | %-12s | \"%s\"",
-				r.Method,
-				wrappedWriter.StatusCode,
-				getRemoteIP(r),
-				truncUser,
-				fmt.Sprintf("%vms", duration.Milliseconds()),
-				fullURL))
+		// Skip logging for '/health' endpoint
```
Comment (gtsteffaniak) [inline backend/http/middleware.go]: can we revert that and instead open an issue to filter api logs?

Some may want this some may not, so we should make it configurable.

Comment (nebula-it) [reply backend/http/middleware.go]: Done

Issue opened [here](https://github.com/gtsteffaniak/filebrowser/issues/2291)

**Comment by Kurami32** [comment]
Just curious but how can I use that dev container?

**Comment by nebula-it** [comment]
If you open this repo in VSCode, it'll show a pop saying it detected a devcontainer file and prompt you to open this folder in a devcontainer.
Then it'll run a docker container with all the dependencies for this project and connect you to that. Its essentially an easier dev environment setup method where all you need is docker pre-installed.
More info [here](https://code.visualstudio.com/docs/devcontainers/containers)

**Comment by Kurami32** [comment]
I didn't knew that, sounds nice, will try it now :)
